# -------------------
# Jekyll Config
# --------------------
url: "https://article.pacificsec.com"
permalink: /:title/
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-environment-variables
  - jekyll-paginate

paginate: 6
paginate_path: "/blog/page/:num"

# Collections
collections_dir: collections
collections:
  posts:
    output: true
    permalink: /blog/:path/

# Pages
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      weight: 999
  - scope:
      path: "images"
    values:
      image: true
  - scope:
      path: "categories"
    values:
      permalink: /category/:basename/
  - scope:
      path: "pages"
    values:
      permalink: /:basename/

# SCSS
sass:
  style: compact

# Excludes
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - netlify.toml

# -------------------
# Theme Config
# --------------------
title: "Pacific Article"
category_dir: "category"

colors:
  #light-mode colors
  primary_bg: "#F5F0E1"
  primary_bg_2: "#eed2d9"
  primary_bg_3: "#D1D5DB59"
  primary_text: "#191a1a"
  base_bg: "#F5F0E1"
  base_bg_2: "#234123"
  base_bg_3: transparent
  base_text: "#191a1a"
  base_text_2: "#555555"
  base_text_3: "#F5F0E1"
  logo_text: "#191a1a"
  menu_text: "#191a1a"
  footer_text_base: "#F5F0E1"
  footer_subscribe_button_text: "#234123"
  base_text_link: "#F6660C"

  # dark-mode colors
  primary_bg_dark: "#121418"
  primary_bg_2_dark: "#eed2d9"
  primary_bg_3_dark: "#24272D"
  primary_text_dark: "#f9fafb"
  base_bg_dark: "#121418"
  base_bg_2_dark: "#1d2026"
  base_bg_3_dark: "#24272d"
  base_text_dark: "#F4F4F5"
  base_text_2_dark: "#D1D5DB"
  base_text_3_dark: "#f9fafb"
  logo_text_dark: "#F4F4F5"
  menu_text_dark: "#F4F4F5"
  footer_text_base_dark: "#f9fafb"
  footer_subscribe_button_text_dark: "#1d2026"
  base_text_link_dark: "#f9fafb"

fonts:
  use_google_fonts: false
  use_self_hosted_fonts: true
  heading: "GT Alpina"
  base: "GT Alpina"
  monospace: "RM Mono"
  logo: "GT Alpina"

logo:
  logo_text: "Pacific"
  logo_image: assets/images/logo/logo.svg
  logo_image_mobile: assets/images/logo/logo-mobile.svg
  logo_image_invert: assets/images/logo/logo-invert.svg
  logo_image_invert_mobile: assets/images/logo/logo-invert-mobile.svg
  logo_image_desktop_height: "32px"
  logo_image_desktop_width: "fit-content"
  logo_image_mobile_height: "28px"
  logo_image_mobile_width: "fit-content"
  show_logo_image_on_mobile: true
  show_logo_image_on_desktop: true
  show_logo_text_on_mobile: false
  show_logo_text_on_desktop: false

header:
  fixed: true

open_graph:
  meta_opengraph_type: "website"
  meta_twitter_card: "summary"
  meta_twitter_site: "@pacific_sec"
  meta_twitter_creator: "@pacific_sec"

darkmode:
  enable_dark_mode: true
  show_dark_mode_toggle_in_header: true
  show_dark_mode_toggle_in_bottom: false # displays the dark mode toggle switch in the footer and allows the user to manually change the mode
  show_dark_mode_toggle_in_mobile_menu: true # displays the dark mode toggle switch in the footer and allows the user to manually change the mode

cookie_banner:
  enabled: true
  show_manage_cookies_at_bottom: true

analytics:
  disable_analytics_on_localhost: false # prevents polluting analytics data while developing but enabling can be useful
  google_analytics_id: "G-1MLMS3EBHT" # G-XXXXXXXXXX
  gtm_id: "GT-MR8688TS" # GTM-XXXXXXXX
  plausible_data_domain: "" # mywebsite.com
  umami_data_website_id: "" # ddd14336-5fb0-4cdd-8f32-e1bfa906cc2b
  umami_src: "" # https://analytics.eu.umami.is/script.js

comments:
  commento:
    enabled: false # you must have a commento account and be on the correct domain. does not work locally.
  disqus:
    shortname: "zerostatic" # Your disqus shortcode for example "zerostatic". leave this blank ie "" to disable.

newsletter:
  mailchimp:
    form_action_url: https://today.us17.list-manage.com/subscribe/post?u=066603f7b7f09d6de8fc448c1&amp;id=2590f5f366&amp;f_id=00c3e4e3f0
    form_title: "Subscribe to Pacific News"

contact_form:
  use_netlify_form: true
  use_formspree_form: false
  formspree_endpoint: https://formspree.io/f/moqyklqv
  netlify_form_name: "contact"

menu:
  show_dropdown_items_in_mobile_menu: false
  show_social_media_in_mobile_menu: true

footer:
  enable_footer: false # show/hide the entire footer
  footer_title: "Pacific Article"
  footer_description: "At Pacific Articles, our team of specialists shares deep insights, professional expertise, and original research in the inherently interdisciplinary field of cybersecurity."
  enable_social_media_icons: false
  enable_menu_footer_primary: false
  enable_menu_footer_secondary: false
  enable_menu_footer_tertiary: false
  footer_primary_menu_title: "Menu 1"
  footer_secondary_menu_title: "Menu 2"
  footer_tertiary_menu_title: "Menu 3"

bottom:
  enable_bottom: true # show/hide the entire bottom (below the footer)
  enable_bottom_menu: true # if enabled, the bottom menu can be edited in `_data/menu.yml`
  copyright_text: "© 2024 Pacific Article"
  show_rss_icon: true
  logo_bottom_image: assets/images/logo/logo-bottom.svg
  logo_bottom_invert_image: assets/images/logo/logo-bottom-invert.svg
